name: Generate Call Graph

on:
  schedule:
    # 毎日午前5時(JST) = UTC 20:00前日
    - cron: '0 20 * * *'
  workflow_dispatch: # 手動実行も可能

jobs:
  check-commits:
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.check.outputs.should-run }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 50 # 過去のコミットを取得

      - name: Check for user commits in last 24 hours
        id: check
        run: |
          # 過去24時間のコミットを取得
          since=$(date -d '24 hours ago' --iso-8601=seconds)
          echo "Checking commits since: $since"

          # 過去24時間のコミットを取得（GitHub Actionsボット以外）
          user_commits=$(git log --since="$since" --pretty=format:"%an" | grep -v "github-actions\[bot\]" | wc -l)

          echo "User commits in last 24 hours: $user_commits"

          if [ "$user_commits" -gt 0 ]; then
            echo "should-run=true" >> $GITHUB_OUTPUT
            echo "Found user commits, proceeding with analysis"
          else
            echo "should-run=false" >> $GITHUB_OUTPUT
            echo "No user commits found, skipping analysis"
          fi

  generate-callgraph:
    needs: check-commits
    if: needs.check-commits.outputs.should-run == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate call graph using simple static analysis
        run: |
          echo "Generating call graph using simple static analysis..."
          node .github/scripts/simple-callgraph.cjs

      - name: Create temporary package.json for script dependencies
        run: |
          mkdir -p .github/temp
          cd .github/temp
          cat > package.json << 'EOF'
          {
            "name": "callgraph-generator",
            "version": "1.0.0",
            "type": "commonjs",
            "dependencies": {
              "cytoscape": "^3.29.2"
            }
          }
          EOF

      - name: Install script dependencies
        run: |
          cd .github/temp
          npm install

      - name: Wait for CodeQL results
        run: sleep 30

      - name: Find and process SARIF results
        run: |
          echo "Looking for SARIF files..."
          find . -name "*.sarif" -type f | head -5

          # CodeQLの結果ファイルを探す
          sarif_file=""
          for file in $(find . -name "*.sarif" -type f); do
            echo "Checking SARIF file: $file"
            if grep -q "callgraph\|function-call-graph" "$file" 2>/dev/null; then
              sarif_file="$file"
              echo "Found callgraph SARIF file: $file"
              break
            fi
          done

          if [ -z "$sarif_file" ]; then
            # フォールバック: 最新のSARIFファイルを使用
            sarif_file=$(find . -name "*.sarif" -type f | head -1)
            echo "Using fallback SARIF file: $sarif_file"
          fi

          if [ -n "$sarif_file" ]; then
            echo "Using SARIF file: $sarif_file"
            echo "=== SARIF file content preview ==="
            head -50 "$sarif_file"
            echo "=== End SARIF preview ==="

            # SARIFファイルからカスタムクエリの結果を抽出してCSVに変換
            node -e "
              const fs = require('fs');
              try {
                const sarif = JSON.parse(fs.readFileSync('$sarif_file', 'utf8'));
                const results = [];

                console.log('SARIF structure:', {
                  hasRuns: !!sarif.runs,
                  runsLength: sarif.runs ? sarif.runs.length : 0
                });

                if (sarif.runs && sarif.runs.length > 0) {
                  sarif.runs.forEach((run, runIndex) => {
                    console.log('Run', runIndex, 'has', run.results ? run.results.length : 0, 'results');

                    if (run.results) {
                      run.results.forEach((result, resultIndex) => {
                        console.log('Result', resultIndex, ':', result.message ? result.message.text : 'no message');

                        if (result.message && result.message.text) {
                          const text = result.message.text;
                          // 'caller -> callee' の形式を期待
                          if (text.includes(' -> ')) {
                            results.push(text);
                            console.log('Added result:', text);
                          } else {
                            console.log('Skipped result (no arrow):', text);
                          }
                        }
                      });
                    }
                  });
                }

                console.log('Total results found:', results.length);

                // CSVヘッダーとデータを出力
                let csv = 'caller,callee\n';
                results.forEach(result => {
                  const parts = result.split(' -> ');
                  if (parts.length === 2) {
                    csv += parts[0].trim() + ',' + parts[1].trim() + '\n';
                  }
                });

                fs.writeFileSync('callgraph.csv', csv);
                console.log('Generated CSV with ' + results.length + ' call relationships');
              } catch (error) {
                console.error('Error processing SARIF:', error);
                // フォールバック: 空のCSVファイルを作成
                fs.writeFileSync('callgraph.csv', 'caller,callee\n');
              }
            "
          else
            echo "No SARIF file found, creating empty CSV"
            echo "caller,callee" > callgraph.csv
          fi

      - name: Generate HTML graph
        run: |
          echo "=== Debug: CSV file content ==="
          if [ -f "callgraph.csv" ]; then
            echo "CSV file exists, content:"
            cat callgraph.csv
            echo "=== End CSV content ==="

            # CSVが空の場合はフォールバック解析を実行
            line_count=$(wc -l < callgraph.csv)
            if [ "$line_count" -le 1 ]; then
              echo "CSV is empty, running fallback analysis..."
              node .github/scripts/simple-callgraph.cjs

              if [ -f "callgraph-simple.csv" ]; then
                echo "Using fallback analysis results"
                cp callgraph-simple.csv callgraph.csv
                echo "Updated CSV content:"
                cat callgraph.csv
              fi
            fi
          else
            echo "CSV file does not exist, running fallback analysis..."
            node .github/scripts/simple-callgraph.cjs

            if [ -f "callgraph-simple.csv" ]; then
              echo "Using fallback analysis results"
              cp callgraph-simple.csv callgraph.csv
            else
              echo "Creating empty CSV as fallback"
              echo "caller,callee" > callgraph.csv
            fi
          fi

          node .github/scripts/convert-to-html.cjs

      - name: Commit and push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"

          # generated-docsディレクトリが存在しない場合は作成
          mkdir -p generated-docs

          # ファイルが変更されているかチェック
          if [ -f "generated-docs/callgraph.html" ]; then
            git add generated-docs/callgraph.html

            if ! git diff --cached --quiet; then
              git commit -m "Update call graph analysis [automated]"
              git push
              echo "Call graph updated and pushed"
            else
              echo "No changes to commit"
            fi
          else
            echo "No callgraph.html file generated"
          fi
